### ISSUE TITLE
 Can I train myself to get the pca parameters? 

### ISSUE THREAD

**Issue by killianMei** [jaeyoon1603/Retrieval-RegionalAttention#3]
This project is great! Can I train myself to get the PCA parameters? How should this be achieved?

**Comment by jaeyoon1603** [comment]
PCA parameters were learned on Landmark dataset that can be found in https://europe.naverlabs.com/Research/Computer-Vision/Learning-Visual-Representations/Deep-Image-Retrieval/
However, it's being corrupted since the dataset has been given by URLs of images.

I recommend you to use another dataset in http://cmp.felk.cvut.cz/cnnimageretrieval/
